version: '3'

services:
  nabla.static.release.x86_64:
    image: artifactory.devsh.eu/nabla/windows/instance:latest
    container_name: dev.nabla.static.release.x86_64.windows
    networks:
      - docker_default
    volumes:
      - type: volume
        source: ssh
        target: ${THIS_PROJECT_SSH_DIRECTORY}
      - type: volume
        source: aritfactory.nabla
        target: ${THIS_PROJECT_ARTIFACTORY_NABLA_DIRECTORY}
      - type: bind
        source: ../../../../../
        target: ${THIS_PROJECT_DOCKER_BIND_DIRECTORY}
    entrypoint: ["build.bat", "--config", "Release", "--arch", "x86_64", "--libType", "static"]
  nabla.static.relwithdebinfo.x86_64:
    image: artifactory.devsh.eu/nabla/windows/instance:latest
    container_name: dev.nabla.static.relwithdebinfo.x86_64.windows
    networks:
      - docker_default
    volumes:
      - type: volume
        source: ssh
        target: ${THIS_PROJECT_SSH_DIRECTORY}
      - type: volume
        source: aritfactory.nabla
        target: ${THIS_PROJECT_ARTIFACTORY_NABLA_DIRECTORY}
      - type: bind
        source: ../../../../../
        target: ${THIS_PROJECT_DOCKER_BIND_DIRECTORY}
    entrypoint: ["build.bat", "--config", "RelWithDebInfo", "--arch", "x86_64", "--libType", "static"]
  nabla.static.debug.x86_64:
    image: artifactory.devsh.eu/nabla/windows/instance:latest
    container_name: dev.nabla.static.debug.x86_64.windows
    networks:
      - docker_default
    volumes:
      - type: volume
        source: ssh
        target: ${THIS_PROJECT_SSH_DIRECTORY}
      - type: volume
        source: aritfactory.nabla
        target: ${THIS_PROJECT_ARTIFACTORY_NABLA_DIRECTORY}
      - type: bind
        source: ../../../../../
        target: ${THIS_PROJECT_DOCKER_BIND_DIRECTORY}
    entrypoint: ["build.bat", "--config", "Debug", "--arch", "x86_64", "--libType", "static"]
  nabla.dynamic.release.x86_64:
    image: artifactory.devsh.eu/nabla/windows/instance:latest
    container_name: dev.nabla.dynamic.release.x86_64.windows
    networks:
      - docker_default
    volumes:
      - type: volume
        source: ssh
        target: ${THIS_PROJECT_SSH_DIRECTORY}
      - type: volume
        source: aritfactory.nabla
        target: ${THIS_PROJECT_ARTIFACTORY_NABLA_DIRECTORY}
      - type: bind
        source: ../../../../../
        target: ${THIS_PROJECT_DOCKER_BIND_DIRECTORY}
    entrypoint: ["build.bat", "--config", "Release", "--arch", "x86_64", "--libType", "dynamic"]
  nabla.dynamic.relwithdebinfo.x86_64:
    image: artifactory.devsh.eu/nabla/windows/instance:latest
    container_name: dev.nabla.dynamic.relwithdebinfo.x86_64.windows
    networks:
      - docker_default
    volumes:
      - type: volume
        source: ssh
        target: ${THIS_PROJECT_SSH_DIRECTORY}
      - type: volume
        source: aritfactory.nabla
        target: ${THIS_PROJECT_ARTIFACTORY_NABLA_DIRECTORY}
      - type: bind
        source: ../../../../../
        target: ${THIS_PROJECT_DOCKER_BIND_DIRECTORY}
    entrypoint: ["build.bat", "--config", "RelWithDebInfo", "--arch", "x86_64", "--libType", "dynamic"]
  nabla.dynamic.debug.x86_64:
    image: artifactory.devsh.eu/nabla/windows/instance:latest
    container_name: dev.nabla.dynamic.debug.x86_64.windows
    networks:
      - docker_default
    volumes:
      - type: volume
        source: ssh
        target: ${THIS_PROJECT_SSH_DIRECTORY}
      - type: volume
        source: aritfactory.nabla
        target: ${THIS_PROJECT_ARTIFACTORY_NABLA_DIRECTORY}
      - type: bind
        source: ../../../../../
        target: ${THIS_PROJECT_DOCKER_BIND_DIRECTORY}
    entrypoint: ["build.bat", "--config", "Debug", "--arch", "x86_64", "--libType", "dynamic"]
networks:
  docker_default:
    external: true
volumes:
    ssh:
      external: true
    aritfactory.nabla:
      external: true