version: '3'

services:
  nabla.checkout:
    image: ${THIS_PROJECT_BASE_IMAGE}
    container_name: dev.nabla.checkout.${THIS_PROJECT_ARCH}.${THIS_PROJECT_PLATFORM}
    hostname: dev.nabla.checkout
    env_file: 
      - ../.env/platform/${THIS_PROJECT_PLATFORM}/.env
    networks:
      nabla.network:
    depends_on:
      nabla.kazoo.server:
        condition: service_healthy
    volumes:
      - type: volume
        source: nabla.repository
        target: ${THIS_PROJECT_NABLA_DIRECTORY}
      - type: volume
        source: ssh
        target: ${THIS_PROJECT_SSH_DIRECTORY}
      - type: bind
        source: ../../../../
        target: ${THIS_PROJECT_DOCKER_BIND_DIRECTORY}
    entrypoint: ["ncpfmp.bat", "nbl.ci.dev.checkout"]
    
networks:
  nabla.network:
    external: true

volumes:
    nabla.repository:
        external: true
    ssh:
      external: true