version: '3'

services:
  nabla.checkout.x86_64:
    image: artifactory.devsh.eu/nabla/windows/base:latest
    container_name: dev.nabla.checkout.x86_64.windows
    hostname: dev.nabla.checkout.windows
    depends_on:
      nabla.kazoo.server.windows:
        condition: service_healthy
    env_file:
      - ../../.env/.env
    volumes:
      - type: volume
        source: nabla.repository
        target: ${THIS_PROJECT_NABLA_DIRECTORY}
      - type: volume
        source: ssh
        target: ${THIS_PROJECT_SSH_DIRECTORY}
      - type: bind
        source: ../../../../../
        target: ${THIS_PROJECT_DOCKER_BIND_DIRECTORY}
    entrypoint: ["ncpfmp.bat", "nbl.ci.dev.checkout"]
volumes:
    nabla.repository:
        external: true
    ssh:
        external: true