version: '3'

services:
  nabla.cpack.static.release.x86_64:
    image: artifactory.devsh.eu/nabla/windows/base:latest
    container_name: dev.nabla.cpack.static.release.x86_64.windows
    hostname: dev.nabla.cpack.static.release.x86_64.windows
    env_file:
      - ../../.env/.env
    volumes:
      - type: volume
        source: nabla.repository
        target: ${THIS_PROJECT_NABLA_DIRECTORY}
      - type: volume
        source: nabla.artifactory
        target: ${THIS_PROJECT_ARTIFACTORY_NABLA_DIRECTORY}
      - type: bind
        source: ../../../../../
        target: ${THIS_PROJECT_DOCKER_BIND_DIRECTORY}
    entrypoint: ["ncpfmp.bat", "nbl.ci.dev.cpack", "--libType", "static", "--config", "Release"]
  nabla.cpack.static.relwithdebinfo.x86_64:
    image: artifactory.devsh.eu/nabla/windows/base:latest
    container_name: dev.nabla.cpack.static.relwithdebinfo.x86_64.windows
    hostname: dev.nabla.cpack.static.relwithdebinfo.x86_64.windows
    env_file:
      - ../../.env/.env
    volumes:
      - type: volume
        source: nabla.repository
        target: ${THIS_PROJECT_NABLA_DIRECTORY}
      - type: volume
        source: nabla.artifactory
        target: ${THIS_PROJECT_ARTIFACTORY_NABLA_DIRECTORY}
      - type: bind
        source: ../../../../../
        target: ${THIS_PROJECT_DOCKER_BIND_DIRECTORY}
    entrypoint: ["ncpfmp.bat", "nbl.ci.dev.cpack", "--libType", "static", "--config", "RelWithDebInfo"]
  nabla.cpack.static.debug.x86_64:
    image: artifactory.devsh.eu/nabla/windows/base:latest
    container_name: dev.nabla.cpack.static.debug.x86_64.windows
    hostname: dev.nabla.cpack.static.debug.x86_64.windows
    env_file:
      - ../../.env/.env
    volumes:
      - type: volume
        source: nabla.repository
        target: ${THIS_PROJECT_NABLA_DIRECTORY}
      - type: volume
        source: nabla.artifactory
        target: ${THIS_PROJECT_ARTIFACTORY_NABLA_DIRECTORY}
      - type: bind
        source: ../../../../../
        target: ${THIS_PROJECT_DOCKER_BIND_DIRECTORY}
    entrypoint: ["ncpfmp.bat", "nbl.ci.dev.cpack", "--libType", "static", "--config", "Debug"]
  nabla.cpack.dynamic.release.x86_64:
    image: artifactory.devsh.eu/nabla/windows/base:latest
    container_name: dev.nabla.cpack.dynamic.release.x86_64.windows
    hostname: dev.nabla.cpack.dynamic.release.x86_64.windows
    env_file:
      - ../../.env/.env
    volumes:
      - type: volume
        source: nabla.repository
        target: ${THIS_PROJECT_NABLA_DIRECTORY}
      - type: volume
        source: nabla.artifactory
        target: ${THIS_PROJECT_ARTIFACTORY_NABLA_DIRECTORY}
      - type: bind
        source: ../../../../../
        target: ${THIS_PROJECT_DOCKER_BIND_DIRECTORY}
    entrypoint: ["ncpfmp.bat", "nbl.ci.dev.cpack", "--libType", "dynamic", "--config", "Release"]
  nabla.cpack.dynamic.relwithdebinfo.x86_64:
    image: artifactory.devsh.eu/nabla/windows/base:latest
    container_name: dev.nabla.cpack.dynamic.relwithdebinfo.x86_64.windows
    hostname: dev.nabla.cpack.dynamic.relwithdebinfo.x86_64.windows
    env_file:
      - ../../.env/.env
    volumes:
      - type: volume
        source: nabla.repository
        target: ${THIS_PROJECT_NABLA_DIRECTORY}
      - type: volume
        source: nabla.artifactory
        target: ${THIS_PROJECT_ARTIFACTORY_NABLA_DIRECTORY}
      - type: bind
        source: ../../../../../
        target: ${THIS_PROJECT_DOCKER_BIND_DIRECTORY}
    entrypoint: ["ncpfmp.bat", "nbl.ci.dev.cpack", "--libType", "dynamic", "--config", "RelWithDebInfo"]
  nabla.cpack.dynamic.debug.x86_64:
    image: artifactory.devsh.eu/nabla/windows/base:latest
    container_name: dev.nabla.cpack.dynamic.debug.x86_64.windows
    hostname: dev.nabla.cpack.dynamic.debug.x86_64.windows
    env_file:
      - ../../.env/.env
    volumes:
      - type: volume
        source: nabla.repository
        target: ${THIS_PROJECT_NABLA_DIRECTORY}
      - type: volume
        source: nabla.artifactory
        target: ${THIS_PROJECT_ARTIFACTORY_NABLA_DIRECTORY}
      - type: bind
        source: ../../../../../
        target: ${THIS_PROJECT_DOCKER_BIND_DIRECTORY}
    entrypoint: ["ncpfmp.bat", "nbl.ci.dev.cpack", "--libType", "dynamic", "--config", "Debug"]
volumes:
    nabla.repository:
        external: true
    nabla.artifactory:
        external: true