version: '3'

services:
  nabla.cmake.static:
    image: ${THIS_PROJECT_BASE_IMAGE}
    container_name: dev.nabla.cmake.static.${THIS_PROJECT_ARCH}.${THIS_PROJECT_PLATFORM}
    hostname: dev.nabla.cmake.static.${THIS_PROJECT_ARCH}.${THIS_PROJECT_PLATFORM}
    env_file: 
      - ../.env/platform/${THIS_PROJECT_PLATFORM}/.env
    networks:
      nabla.network:
    depends_on:
      nabla.submodules:
        condition: service_completed_successfully
    volumes:
      - type: volume
        source: nabla.repository
        target: ${THIS_PROJECT_NABLA_DIRECTORY}
      - type: volume
        source: ssh
        target: ${THIS_PROJECT_SSH_DIRECTORY}
      - type: bind
        source: ../../../../
        target: ${THIS_PROJECT_DOCKER_BIND_DIRECTORY}
    entrypoint: ["ncpfmp.bat", "nbl.ci.dev.cmake", "--libType", "static"]
  nabla.cmake.dynamic:
    image: ${THIS_PROJECT_BASE_IMAGE}
    container_name: dev.nabla.cmake.dynamic.${THIS_PROJECT_ARCH}.${THIS_PROJECT_PLATFORM}
    hostname: dev.nabla.cmake.dynamic.${THIS_PROJECT_ARCH}.${THIS_PROJECT_PLATFORM}
    env_file: 
      - ../.env/platform/${THIS_PROJECT_PLATFORM}/.env
    networks:
      nabla.network:
    depends_on:
      nabla.submodules:
        condition: service_completed_successfully
    volumes:
      - type: volume
        source: nabla.repository
        target: ${THIS_PROJECT_NABLA_DIRECTORY}
      - type: volume
        source: ssh
        target: ${THIS_PROJECT_SSH_DIRECTORY}
      - type: bind
        source: ../../../../
        target: ${THIS_PROJECT_DOCKER_BIND_DIRECTORY}
    entrypoint: ["ncpfmp.bat", "nbl.ci.dev.cmake", "--libType", "dynamic"]
    
networks:
  nabla.network:
    external: true

volumes:
    nabla.repository:
        external: true
    ssh:
      external: true