version: '3'

services:
  nabla.cmake.static.x86_64:
    image: artifactory.devsh.eu/nabla/windows/base:latest
    container_name: dev.nabla.cmake.static.x86_64.windows
    hostname: dev.nabla.cmake.static.x86_64.windows
    env_file:
      - ../../.env/.env
    depends_on:
      nabla.submodules.x86_64.windows:
        condition: service_completed_successfully
    volumes:
      - type: volume
        source: nabla.repository
        target: ${THIS_PROJECT_NABLA_DIRECTORY}
      - type: volume
        source: ssh
        target: ${THIS_PROJECT_SSH_DIRECTORY}
      - type: bind
        source: ../../../../../
        target: ${THIS_PROJECT_DOCKER_BIND_DIRECTORY}
    entrypoint: ["ncpfmp.bat", "nbl.ci.dev.cmake", "--arch", "x86_64", "--libType", "static"]
  nabla.cmake.dynamic.x86_64:
    image: artifactory.devsh.eu/nabla/windows/base:latest
    container_name: dev.nabla.cmake.dynamic.x86_64.windows
    hostname: dev.nabla.cmake.dynamic.x86_64.windows
    depends_on:
      nabla.submodules.x86_64.windows:
        condition: service_completed_successfully
    env_file:
      - ../../.env/.env
    volumes:
      - type: volume
        source: nabla.repository
        target: ${THIS_PROJECT_NABLA_DIRECTORY}
      - type: volume
        source: ssh
        target: ${THIS_PROJECT_SSH_DIRECTORY}
      - type: bind
        source: ../../../../../
        target: ${THIS_PROJECT_DOCKER_BIND_DIRECTORY}
    environment:
      - BUILD_SCRIPT_ARGS=${BUILD_SCRIPT_ARGS}
    entrypoint: ["ncpfmp.bat", "nbl.ci.dev.cmake", "--arch", "x86_64", "--libType", "dynamic"]
volumes:
    nabla.repository:
        external: true
    ssh:
      external: true