version: '3'

services:
  base:
    build:
      context: ../
      args:
      - THIS_PROJECT_WORKING_DIRECTORY=${THIS_PROJECT_WORKING_DIRECTORY}
      - THIS_PROJECT_NABLA_DIRECTORY=${THIS_PROJECT_NABLA_DIRECTORY}
      - THIS_PROJECT_DOCKER_BIND_DIRECTORY=${THIS_PROJECT_DOCKER_BIND_DIRECTORY}
    environment:
    - THIS_PROJECT_WORKING_DIRECTORY=${THIS_PROJECT_WORKING_DIRECTORY}
    - THIS_PROJECT_NABLA_DIRECTORY=${THIS_PROJECT_NABLA_DIRECTORY}
    - THIS_PROJECT_DOCKER_BIND_DIRECTORY=${THIS_PROJECT_DOCKER_BIND_DIRECTORY}
    - BUILD_SCRIPT_ARGS=${BUILD_SCRIPT_ARGS}
    image: artifactory.devsh.eu/nabla/windows/base:latest
    container_name: dev.nabla.base.x86_64.windows
    hostname: dev.nabla.base.x86_64.windows
    networks:
      net:
        ipv4_address: 172.28.5.2
    volumes:
      - type: bind
        source: ../../../../
        target: ${THIS_PROJECT_DOCKER_BIND_DIRECTORY}
      - type: volume
        source: ssh
        target: ${THIS_PROJECT_SSH_DIRECTORY}
    entrypoint: ["build.bat", "--init-clone-generate-directories", "True", "%BUILD_SCRIPT_ARGS%"]
    ports:
      - "5678:5678"
networks:
  net:
    name: nablaNetwork
    driver: nat
    ipam:
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.5.1
volumes:
    ssh:
      external: true