version: '3'

services:
  nabla.init:
    build:
      context: ../../../
      args:
      - THIS_PROJECT_DOCKER_BIND_DIRECTORY=${THIS_PROJECT_DOCKER_BIND_DIRECTORY}
    env_file: 
      - ../.env/platform/${THIS_PROJECT_PLATFORM}/.env
    image: ${THIS_PROJECT_BASE_IMAGE}
    container_name: dev.nabla.init.${THIS_PROJECT_ARCH}.${THIS_PROJECT_PLATFORM}
    hostname: dev.nabla.init.${THIS_PROJECT_ARCH}.${THIS_PROJECT_PLATFORM}
    networks:
      nabla.network:
    volumes:
      - type: volume
        source: nabla.repository
        target: ${THIS_PROJECT_NABLA_DIRECTORY}
      - type: volume
        source: nabla.artifactory
        target: ${THIS_PROJECT_ARTIFACTORY_NABLA_DIRECTORY}
      - type: volume
        source: ssh
        target: ${THIS_PROJECT_SSH_DIRECTORY}
      - type: bind
        source: ../../../../
        target: ${THIS_PROJECT_DOCKER_BIND_DIRECTORY}
    entrypoint: ["ncpfmp.bat", "nbl.ci.dev.init"]
    
networks:
  nabla.network:
    external: true

volumes:
    nabla.repository:
        external: true
    nabla.artifactory:
        external: true
    ssh:
      external: true