name: Shallow Nabla + Cache (with checkout)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  nabla-checkout:
    runs-on: windows-2022
    steps:
      - name: Restore mirror cache
        uses: actions/cache/restore@v4
        with:
          path: ${{ runner.temp }}\git-mirror\nabla.git
          key: nabla-mirror-
          restore-keys: |
            nabla-mirror-

      - name: Checkout
        shell: pwsh
        run: |
          @'
          [url "https://github.com/"]
              insteadOf = git@github.com:
          [protocol]
              version = 2
          [fetch]
              parallel = 64
          [checkout]
              workers = 16
          [http]
              version = HTTP/2
          '@ | Set-Content "$env:USERPROFILE\.gitconfig"

          $mirrorRoot = Join-Path $env:RUNNER_TEMP 'git-mirror'
          $mirrorRepo = Join-Path $mirrorRoot 'nabla.git'
          if (-not (Test-Path $mirrorRoot)) { New-Item -ItemType Directory -Path $mirrorRoot | Out-Null }
          if (-not (Test-Path $mirrorRepo)) {
            git clone --mirror --filter=blob:none https://github.com/Devsh-Graphics-Programming/Nabla.git $mirrorRepo
          }
          git --git-dir $mirrorRepo fetch --filter=blob:none --no-tags --force origin master

          git clone --filter=blob:none --no-checkout `
            --reference-if-able $mirrorRepo --dissociate `
            https://github.com/Devsh-Graphics-Programming/Nabla.git .

          git fetch --depth=1 origin $env:GITHUB_REF
          git checkout FETCH_HEAD

      - name: Restore submodules cache
        uses: actions/cache/restore@v4
        with:
          path: .git\modules
          key: nabla-mirror-
          restore-keys: |
            nabla-mirror-

      - name: Init submodules (shallow)
        shell: pwsh
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive --depth 1 --jobs 64 --recommend-shallow

      - name: Save cache (mirror + modules, only master)
        if: github.ref == 'refs/heads/master'
        uses: actions/cache/save@v4
        with:
          path: |
            ${{ runner.temp }}\git-mirror\nabla.git
            .git\modules
          key: nabla-mirror-${{ github.run_id }}
