name: Shallow Nabla + Cache (with checkout)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  nabla-checkout:
    runs-on: windows-2022
    steps:
      - name: Checkout (shallow, no submodules)
        uses: actions/checkout@v4
        with:
          repository: Devsh-Graphics-Programming/Nabla
          ref: master
          fetch-depth: 1
          submodules: 'false'
          filter: blob:none
          show-progress: false

      - name: Restore git objects cache
        uses: actions/cache/restore@v4
        with:
          path: |
            .git-mirror/nabla.git
            .git/modules
          key: nabla-mirror-
          restore-keys: |
            nabla-mirror-

      - name: Ensure mirror up-to-date (master only)
        shell: pwsh
        run: |
          if (-not (Test-Path '.git-mirror')) { New-Item -ItemType Directory -Path .git-mirror | Out-Null }
          if (-not (Test-Path '.git-mirror/nabla.git')) {
            git clone --mirror --filter=blob:none https://github.com/Devsh-Graphics-Programming/Nabla.git .git-mirror/nabla.git
          }
          git --git-dir .git-mirror/nabla.git fetch --filter=blob:none --no-tags --force origin master

      - name: Init submodules (shallow + parallel)
        shell: pwsh
        run: |
          git config --global url."https://github.com/".insteadOf "git@github.com:"
          git config --global protocol.version 2
          git config --global fetch.parallel 64
          git config --global checkout.workers 16
          git config --global http.version HTTP/2
          git submodule sync --recursive
          git -c submodule.alternateLocation=superproject -c submodule.alternateErrorStrategy=info -c submodule.fetchJobs=64 submodule update --init --recursive --depth 1 --jobs 64 --recommend-shallow

      - name: Save git objects cache (only master from upstream)
        if: github.ref == 'refs/heads/master'
        uses: actions/cache/save@v4
        with:
          path: |
            .git-mirror/nabla.git
            .git/modules
          key: nabla-mirror-${{ github.run_id }}
