name: Shallow Nabla + Cache (with checkout)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  nabla-checkout:
    runs-on: ubuntu-22.04
    steps:
      - name: Init Git
        shell: bash
        run: |
          git init .
          git remote add origin https://github.com/Devsh-Graphics-Programming/Nabla.git

      - name: Restore git objects cache
        uses: actions/cache/restore@v4
        with:
          path: |
            .git-mirror/nabla.git
            .git/modules
          key: nabla-mirror-
          restore-keys: |
            nabla-mirror-

      - name: Checkout (mirror + submodules shallow)
        shell: bash
        env:
          GIT_OPTIONAL_LOCKS: "0"
          GIT_ATTR_NOSYSTEM: "1"
          GIT_TERMINAL_PROMPT: "0"
          GCM_INTERACTIVE: "never"
          GIT_CEILING_DIRECTORIES: ${{ github.workspace }}
        run: |
          git config --global url."https://github.com/".insteadOf git@github.com:
          git config --global url."https://github.com/".insteadOf ssh://git@github.com/
          git config --global protocol.version 2
          git config --global fetch.parallel 64
          git config --global checkout.workers 16
          git config --global http.version HTTP/2
          git config --global core.fscache true
          git config --global core.preloadindex true
          git config --global core.autocrlf false
          git config --global core.symlinks true
          git config --global core.ignoreStatUnchanged true
          git config --global gc.auto 0
          git config --global index.threads 16

          mkdir -p .git-mirror
          if [ ! -d ".git-mirror/nabla.git" ]; then
            git clone --mirror --filter=blob:none https://github.com/Devsh-Graphics-Programming/Nabla.git .git-mirror/nabla.git
          fi

          git --git-dir .git-mirror/nabla.git fetch --filter=blob:none --no-tags --force origin master

          git fetch --depth=1 origin "$GITHUB_REF"
          git checkout FETCH_HEAD

          git submodule sync --recursive
          git -c submodule.alternateLocation=superproject \
              -c submodule.alternateErrorStrategy=info \
              -c submodule.fetchJobs=64 \
              -c url.https://github.com/.insteadof=git@github.com: \
              -c url.https://github.com/.insteadof=ssh://git@github.com/ \
              submodule update --init --recursive --depth 1 --jobs 64 --recommend-shallow

      - name: Save git objects cache (only master from upstream)
        if: github.ref == 'refs/heads/master'
        uses: actions/cache/save@v4
        with:
          path: |
            .git-mirror/nabla.git
            .git/modules
          key: nabla-mirror-${{ github.run_id }}
