name: Shallow Nabla + Cache (with checkout)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  nabla-checkout:
    runs-on: windows-2022
    steps:
      - name: Restore git objects cache
        uses: actions/cache/restore@v4
        with:
          path: |
            .git-mirror/nabla.git
            wt/.git/modules
          key: nabla-mirror-
          restore-keys: |
            nabla-mirror-

      - name: Submodules (shallow + alternates)
        shell: pwsh
        run: |
          if (-not (Test-Path '.git-mirror')) { New-Item -ItemType Directory -Path .git-mirror | Out-Null }
          if (-not (Test-Path '.git-mirror/nabla.git')) {
            git clone --mirror --filter=blob:none https://github.com/Devsh-Graphics-Programming/Nabla.git .git-mirror/nabla.git
          }
          git -c fetch.parallel=64 -c http.version=HTTP/2 -c protocol.version=2 --git-dir .git-mirror/nabla.git fetch --filter=blob:none --no-tags --force origin +$env:GITHUB_REF:$env:GITHUB_REF
          if (Test-Path 'wt') { Remove-Item -Recurse -Force 'wt' }
          git -c checkout.workers=16 --git-dir .git-mirror/nabla.git worktree add --force --detach wt $env:GITHUB_SHA
          git -C wt submodule sync --recursive
          git -C wt `
            -c fetch.parallel=64 `
            -c checkout.workers=16 `
            -c http.version=HTTP/2 `
            -c protocol.version=2 `
            -c submodule.fetchJobs=64 `
            -c submodule.alternateLocation=superproject `
            -c submodule.alternateErrorStrategy=info `
            -c url.https://github.com/.insteadof=git@github.com: `
            -c url.https://github.com/.insteadof=ssh://git@github.com/ `
            submodule update --init --recursive --depth 1 --jobs 64 --recommend-shallow

      - name: Save git objects cache (only master from upstream)
        if: github.ref == 'refs/heads/master'
        uses: actions/cache/save@v4
        with:
          path: |
            .git-mirror/nabla.git
            wt/.git/modules
          key: nabla-mirror-${{ github.run_id }}
