name: Shallow Nabla + Cache (with checkout)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  nabla-checkout:
    runs-on: windows-2022
    steps:
      - name: Restore git objects cache
        uses: actions/cache/restore@v4
        with:
          path: |
            .git-mirror/nabla.git
            .git/modules
          key: nabla-mirror-
          restore-keys: |
            nabla-mirror-

      - name: Checkout
        shell: pwsh
        run: |
          @'
          [url "https://github.com/"]
              insteadOf = git@github.com:
          [protocol]
              version = 2
          [fetch]
              parallel = 64
          [checkout]
              workers = 16
          [http]
              version = HTTP/2
          '@ | Set-Content "$env:USERPROFILE\.gitconfig"

          git clone --filter=blob:none --no-checkout `
            --reference-if-able .git-mirror/nabla.git --dissociate `
            https://github.com/Devsh-Graphics-Programming/Nabla.git .

          if (-not (Test-Path '.git-mirror')) { New-Item -ItemType Directory -Path .git-mirror | Out-Null }
          if (-not (Test-Path '.git-mirror/nabla.git')) {
            git clone --mirror --filter=blob:none https://github.com/Devsh-Graphics-Programming/Nabla.git .git-mirror/nabla.git
          }
          git --git-dir .git-mirror/nabla.git fetch --filter=blob:none --no-tags --force origin master

          git fetch --depth=1 origin $env:GITHUB_REF
          git checkout FETCH_HEAD

          git submodule sync --recursive
          git submodule update --init --recursive --depth 1 --jobs 64 --recommend-shallow

      - name: Save git objects cache
        if: github.ref == 'refs/heads/master'
        uses: actions/cache/save@v4
        with:
          path: |
            .git-mirror/nabla.git
            .git/modules
          key: nabla-mirror-${{ github.run_id }}
